version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./source:/app/source 
    # env_file:
    #   - .env
    ports:
      - "5013:5000"
    networks:
      - off_fake_api_net

networks:
  off_fake_api_net:
    external: true
